# Generated by Django 5.1.2 on 2024-12-07 15:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administratif',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='administratif',
            name='prenom',
        ),
        migrations.RemoveField(
            model_name='medcin',
            name='administratif',
        ),
        migrations.RemoveField(
            model_name='medcin',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='prenom',
        ),
        migrations.AddField(
            model_name='medcin',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='medcin',
            name='date_naissance',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='medcin',
            name='medcin_traitant',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='medcin',
            name='mutuelle',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='medcin',
            name='nss',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='medcin',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
