# Generated by Django 5.1.3 on 2024-12-28 14:05

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_consultation_resume_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordonnance',
            name='date',
        ),
        migrations.AlterField(
            model_name='consultation',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='resume',
            name='consul',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.consultation'),
        ),
    ]
