# Generated by Django 5.1.2 on 2024-12-08 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_administratif_nom_remove_administratif_prenom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Administratif', 'administratif'), ('Patient', 'patient'), ('Medcin', 'medcin')], max_length=30),
        ),
    ]
