# Generated by Django 5.1.2 on 2024-12-09 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='patient',
            table='custom_person',
        ),
    ]
