# Generated by Django 5.1.3 on 2024-12-28 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_ordonnance_date_alter_consultation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='medcin_traitant',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='med_traitant', to='api.medcin'),
        ),
    ]
