# Generated by Django 5.1.3 on 2024-12-28 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_patient_medcin_traitant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='medcin_traitant',
        ),
    ]
