# Generated by Django 5.1.2 on 2024-12-12 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_medcin_medcin_traitant_remove_medcin_mutuelle_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='patient',
            table=None,
        ),
    ]
