# Generated by Django 5.1.4 on 2024-12-26 14:45

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_patient_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bilan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('trouveDiagnostic', models.BooleanField(default=False)),
                ('raison_admission', models.TextField()),
                ('medcin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.medcin')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Soin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeSoin', models.TextField()),
                ('descriptionSoin', models.TextField()),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('infermier', models.ManyToManyField(related_name='soins', to='api.infirmier')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.patient')),
            ],
        ),
        migrations.CreateModel(
            name='DPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateAddmition', models.DateTimeField(default=datetime.datetime.now)),
                ('dateSortie', models.DateTimeField(auto_now=True)),
                ('dateMaj', models.DateTimeField(default=datetime.datetime.now)),
                ('bilan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.bilan')),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.consultation')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.patient')),
                ('ordonnance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ordonnance')),
                ('antecedents_medicaux', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.resume')),
                ('soins', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.soin')),
            ],
        ),
    ]
