# Generated by Django 5.1.3 on 2024-12-28 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_patient_medcin_traitant'),
    ]

    operations = [
        migrations.AddField(
            model_name='bilanbiologique',
            name='consul',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.consultation'),
        ),
        migrations.AddField(
            model_name='bilanradiologique',
            name='consul',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.consultation'),
        ),
    ]
