# Generated by Django 5.1.4 on 2024-12-27 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_dpi_medcin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dpi',
            name='antecedents_medicaux',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RenameField(
            model_name='dpi',
            old_name='dateAddmition',
            new_name='dateAdmission',
        ),
        migrations.RemoveField(
            model_name='dpi',
            name='medcin',
        ),
        migrations.RemoveField(
            model_name='dpi',
            name='patient',
        ),
        migrations.AddField(
            model_name='patient',
            name='dossier',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.dpi'),
        ),
        migrations.DeleteModel(
            name='Resume',
        ),
    ]
