# Generated by Django 5.1.3 on 2024-12-28 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_patient_medcin_traitant'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='medecins_traitants',
            field=models.ManyToManyField(blank=True, related_name='patients', to='api.medcin'),
        ),
    ]
