# Generated by Django 5.1.4 on 2024-12-30 00:14

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_dpi_antecedents_medicaux_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dpi',
            name='bilan',
        ),
        migrations.RemoveField(
            model_name='dpi',
            name='consultation',
        ),
        migrations.RemoveField(
            model_name='dpi',
            name='observation',
        ),
        migrations.RemoveField(
            model_name='dpi',
            name='ordonnance',
        ),
        migrations.RemoveField(
            model_name='dpi',
            name='soins',
        ),
        migrations.AddField(
            model_name='consultation',
            name='dateProchaineCons',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='consultation',
            name='soins',
            field=models.ManyToManyField(related_name='consultations', to='api.soin'),
        ),
        migrations.AddField(
            model_name='dpi',
            name='bilans',
            field=models.ManyToManyField(related_name='dpis', to='api.bilan'),
        ),
        migrations.AddField(
            model_name='dpi',
            name='consultations',
            field=models.ManyToManyField(related_name='dpis', to='api.consultation'),
        ),
        migrations.AddField(
            model_name='dpi',
            name='observations',
            field=models.ManyToManyField(related_name='dpis', to='api.observation'),
        ),
        migrations.AddField(
            model_name='dpi',
            name='ordonnances',
            field=models.ManyToManyField(related_name='dpis', to='api.ordonnance'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='medcin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.medcin'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.patient'),
        ),
    ]
