# Generated by Django 5.1.3 on 2024-12-28 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_patient_medecins_traitants'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='medcin_traitant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.medcin'),
        ),
    ]
