# Generated by Django 5.1.4 on 2024-12-30 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_dpi_bilan_remove_dpi_consultation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedcalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parametre', models.CharField(max_length=100)),
                ('value', models.FloatField()),
                ('unite', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('dose', models.CharField(max_length=50)),
                ('frequence', models.CharField(choices=[('matin', 'Matin'), ('midi', 'Midi'), ('soir', 'Soir'), ('matin_midi', 'Matin et Midi'), ('midi_soir', 'Midi et Soir'), ('matin_midi_soir', 'Matin, Midi et Soir'), ('au_besoin', 'Au besoin')], max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='dpi',
            name='bilans',
        ),
        migrations.AddField(
            model_name='ordonnance',
            name='consul',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consul_ord', to='api.consultation'),
        ),
        migrations.AddField(
            model_name='ordonnance',
            name='duree',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ordonnance',
            name='etat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordonnance',
            name='medecin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medecin_ord', to='api.medcin'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='dossier',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_dossier', to='api.dpi'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='medcin_traitant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.medcin'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='nss',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.CreateModel(
            name='BilanBiologique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date_prescription', models.DateField()),
                ('typeBilan', models.CharField(choices=[('BIOLOGIQUE', 'Biologique'), ('RADIOLOGIQUE', 'Radiologique')], default='', max_length=100)),
                ('consul', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.consultation')),
                ('laborantin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='labo_bilan', to='api.laborantin')),
                ('resultats_analytiques', models.ManyToManyField(related_name='result_bilan', to='api.medcalrecord')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='dpi',
            name='bilanBiologiques',
            field=models.ManyToManyField(blank=True, related_name='dpis', to='api.bilanbiologique'),
        ),
        migrations.CreateModel(
            name='BilanRadiologique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date_prescription', models.DateField()),
                ('typeBilan', models.CharField(choices=[('BIOLOGIQUE', 'Biologique'), ('RADIOLOGIQUE', 'Radiologique')], default='', max_length=100)),
                ('images', models.JSONField(blank=True, default=list, null=True)),
                ('compte_rendu', models.TextField(blank=True, null=True)),
                ('consul', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.consultation')),
                ('radiologue', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='radio_bilan', to='api.radiologue')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='dpi',
            name='bilanRadiologiques',
            field=models.ManyToManyField(blank=True, related_name='dpis', to='api.bilanradiologique'),
        ),
        migrations.AddField(
            model_name='ordonnance',
            name='medicaments',
            field=models.ManyToManyField(blank=True, related_name='ordonnances', to='api.medicament'),
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptomes', models.CharField(max_length=100)),
                ('dateProchaineConsul', models.DateField()),
                ('consul', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.consultation')),
                ('mesuresPrises', models.ManyToManyField(related_name='resume', to='api.medcalrecord')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.patient')),
            ],
        ),
        migrations.DeleteModel(
            name='Bilan',
        ),
    ]
