# Generated by Django 5.1.3 on 2025-01-01 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_ordonnance_commentairesvalidation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bilanradiologique',
            old_name='images',
            new_name='resultats',
        ),
        migrations.AlterField(
            model_name='bilanbiologique',
            name='date_prescription',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='bilanradiologique',
            name='date_prescription',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
