# Generated by Django 5.1.3 on 2025-01-01 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_bilanbiologique_laborantin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bilanbiologique',
            name='laborantin',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labo_bilan', to='api.laborantin'),
        ),
        migrations.AlterField(
            model_name='bilanradiologique',
            name='radiologue',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='radio_bilan', to='api.radiologue'),
        ),
    ]
