# Generated by Django 5.1.3 on 2025-01-01 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_bilanbiologique_laborantin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bilanbiologique',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='bilanradiologique',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='bilanbiologique',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bilanradiologique',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
