# Generated by Django 5.1.4 on 2025-01-03 15:21

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_bilanbiologique_medcin_bilanradiologique_medcin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(default=0.0)),
                ('tension', models.FloatField(default=0.0)),
                ('frequanceCardiaque', models.FloatField(default=0.0)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='soin',
        ),
        migrations.RemoveField(
            model_name='ordonnance',
            name='date',
        ),
        migrations.RemoveField(
            model_name='ordonnance',
            name='medcin',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='date_prochin',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='diagnostic',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='mesures',
        ),
        migrations.RemoveField(
            model_name='soin',
            name='infirmier',
        ),
        migrations.RemoveField(
            model_name='soin',
            name='observation',
        ),
        migrations.AddField(
            model_name='consultation',
            name='dateProchaineCons',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='consultation',
            name='patient',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.patient'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='raison_admission',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='soins',
            field=models.ManyToManyField(related_name='consultations', to='api.soin'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='trouveDiagnostic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordonnance',
            name='commentairesValidation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordonnance',
            name='consul',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consul_ord', to='api.consultation'),
        ),
        migrations.AddField(
            model_name='ordonnance',
            name='dateCreation',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ordonnance',
            name='dateValidation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordonnance',
            name='duree',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ordonnance',
            name='etat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordonnance',
            name='medecin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medecin_ord', to='api.medcin'),
        ),
        migrations.AddField(
            model_name='resume',
            name='consul',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.consultation'),
        ),
        migrations.AddField(
            model_name='resume',
            name='mesuresPrises',
            field=models.ManyToManyField(related_name='resume', to='api.medcalrecord'),
        ),
        migrations.AddField(
            model_name='soin',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='soin',
            name='descriptionSoin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soin',
            name='infermier',
            field=models.ManyToManyField(related_name='soins', to='api.infirmier'),
        ),
        migrations.AddField(
            model_name='soin',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.patient'),
        ),
        migrations.AddField(
            model_name='soin',
            name='typeSoin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='medcin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.medcin'),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='frequence',
            field=models.CharField(choices=[('matin', 'Matin'), ('midi', 'Midi'), ('soir', 'Soir'), ('matin_midi', 'Matin et Midi'), ('midi_soir', 'Midi et Soir'), ('matin_midi_soir', 'Matin, Midi et Soir'), ('au_besoin', 'Au besoin')], max_length=50),
        ),
        migrations.AlterField(
            model_name='resume',
            name='symptomes',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='DPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antecedents_medicaux', models.TextField(blank=True, null=True)),
                ('dateAdmission', models.DateField(default=django.utils.timezone.now)),
                ('dateSortie', models.DateTimeField(auto_now=True)),
                ('dateMaj', models.DateTimeField(default=datetime.datetime.now)),
                ('bilanBiologiques', models.ManyToManyField(blank=True, related_name='sejour_bilanBio', to='api.bilanbiologique')),
                ('bilanRadiologiques', models.ManyToManyField(blank=True, related_name='sejour_bilanRadio', to='api.bilanradiologique')),
                ('consultations', models.ManyToManyField(blank=True, related_name='cons_dossier', to='api.consultation')),
                ('ordonnances', models.ManyToManyField(blank=True, related_name='sejour_ord', to='api.ordonnance')),
                ('observations', models.ManyToManyField(blank=True, related_name='dpis', to='api.observation')),
            ],
        ),
        migrations.AlterField(
            model_name='patient',
            name='dossier',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_dossier', to='api.dpi'),
        ),
        migrations.DeleteModel(
            name='Dossier',
        ),
    ]
