# Generated by Django 5.1.3 on 2025-01-01 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_bilanbiologique_status_bilanradiologique_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bilanbiologique',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='bilanradiologique',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='', max_length=100),
        ),
    ]
