# Generated by Django 5.1.3 on 2024-12-09 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('dose', models.CharField(max_length=50)),
                ('frequence', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('id_ord', models.AutoField(primary_key=True, serialize=False)),
                ('medicament', models.ManyToManyField(to='api.medicament')),
            ],
        ),
    ]
