# Generated by Django 5.1.3 on 2024-12-09 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BilanBiologique',
            fields=[
                ('id_bilan', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('date_prescription', models.DateField()),
                ('medecin', models.CharField(max_length=200)),
                ('biologist', models.CharField(max_length=200)),
                ('resultats_analytiques', models.JSONField(default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BilanRadiologique',
            fields=[
                ('id_bilan', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('date_prescription', models.DateField()),
                ('medecin', models.CharField(max_length=200)),
                ('radiologue', models.CharField(max_length=200)),
                ('images', models.JSONField(default=list)),
                ('compte_rendu', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
