# Generated by Django 5.1.3 on 2024-12-12 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_bilanbiologique_bilanradiologique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordonnance',
            name='medicament',
        ),
        migrations.AddField(
            model_name='ordonnance',
            name='medicament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.medicament'),
        ),
    ]
