# Generated by Django 5.1.3 on 2024-12-14 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_ordonnance_medicament_ordonnance_medicament'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id_medRecord', models.AutoField(primary_key=True, serialize=False)),
                ('parametre', models.CharField(max_length=100)),
                ('value', models.FloatField()),
                ('unite', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='bilanbiologique',
            name='resultats_analytiques',
        ),
        migrations.AlterField(
            model_name='bilanbiologique',
            name='type',
            field=models.CharField(choices=[('Biologique', 'Biologique'), ('Radiologique', 'Radiologique')], default='Biologique', max_length=50),
        ),
        migrations.AlterField(
            model_name='bilanradiologique',
            name='type',
            field=models.CharField(choices=[('Biologique', 'Biologique'), ('Radiologique', 'Radiologique')], default='Biologique', max_length=50),
        ),
        migrations.AddField(
            model_name='bilanbiologique',
            name='resultats_analytiques',
            field=models.ManyToManyField(related_name='bilans', to='api.medicalrecord'),
        ),
    ]
