# Generated by Django 5.1.3 on 2024-12-14 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_medicalrecord_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordonnance',
            name='medicament',
        ),
        migrations.AddField(
            model_name='ordonnance',
            name='medicaments',
            field=models.ManyToManyField(related_name='ordonnances', to='api.medicament'),
        ),
    ]
